/*
 * Created on Jan 10, 2006
 *
 */
package org.codehaus.mojo.simian;

import au.com.redhillconsulting.simian.SourceFile;

/**
 * Simple class to hold information on a record of the simian repor
 * 
 * @author mgriffa
 * @version $Id$
 */
public class Record
{
    private SourceFile sourcefile;

    private int startLine;

    private int endLine;

    private boolean subsumed;

    private int blockSize;

    private int blockId;

    private boolean visited;

    public boolean isVisited()
    {
        return visited;
    }

    public void setVisited( boolean visited )
    {
        this.visited = visited;
    }

    public int getBlockId()
    {
        return blockId;
    }

    public void setBlockId( int blockId )
    {
        this.blockId = blockId;
    }

    public int getBlockSize()
    {
        return blockSize;
    }

    public void setBlockSize( int blockSize )
    {
        this.blockSize = blockSize;
    }

    public int getEndLine()
    {
        return endLine;
    }

    public void setEndLine( final int endLine )
    {
        this.endLine = endLine;
    }

    public SourceFile getSourcefile()
    {
        return sourcefile;
    }

    public void setSourcefile( final SourceFile sourcefile )
    {
        this.sourcefile = sourcefile;
    }

    public int getStartLine()
    {
        return startLine;
    }

    public void setStartLine( final int startLine )
    {
        this.startLine = startLine;
    }

    public boolean isSubsumed()
    {
        return subsumed;
    }

    public void setSubsumed( final boolean subsumed )
    {
        this.subsumed = subsumed;
    }

    /**
     * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

    public String toString()
    {
        StringBuffer buffer = new StringBuffer();
        buffer.append( "[Record:" );
        buffer.append( " sourcefile: " );
        buffer.append( sourcefile.getFilename() );
        buffer.append( " startLine: " );
        buffer.append( startLine );
        buffer.append( " endLine: " );
        buffer.append( endLine );
        buffer.append( " subsumed: " );
        buffer.append( subsumed );
        buffer.append( " blockSize: " );
        buffer.append( blockSize );
        buffer.append( " blockId: " );
        buffer.append( blockId );
        buffer.append( "]" );
        return buffer.toString();
    }
}
